export const auth_types = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  REGISTER_USER: "REGISTER_USER",
  AUTH_ERROR: "AUTH_ERROR",
  KEEP_LOGIN: "KEEP_LOGIN",
  EDIT_USER: "EDIT_USER",
};
